### ISSUE TITLE
can you explain the the theory why this can work?

### ISSUE THREAD

**Issue by sigusr1** [cvra/arm-cortex-tools#3]
can you explain the the theory why this can work? Thanks.

**Comment by antoinealb** [comment]
Hi,
Sorry for the delayed answer.

This repository contains code for two different functionality:

1. The first one is a driver for the [Cortex-M Memory Protection Unit (MPU)](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0439b/Chdecfea.html). You can read more about what a MPU does on [Wikipedia](https://en.wikipedia.org/wiki/Memory_protection_unit)
2. The other function is some code to help debugging [Cortex-M faults](https://developer.arm.com/docs/dui0553/latest/the-cortex-m4-processor/fault-handling/fault-types). This codes help debug such faults by providing information about this fault such as the instruction that created it, its address, register values, and so on.

Both were mostly written using the datasheet for the Cortex-M cores, which should explain a bit how this works. If you have a more specific question, feel free to reopen this issue :)
